In [35]:
##Q1
import numpy as np

A=np.random.randint(0,128, size=(3,6))
B=np.random.randint(0,128, size=(3,6))
print(A)
#plt.imshow(A)
A.tolist()

[[  3   2  76 100  54  43]
 [102  85  25  61  51  75]
 [ 10  67  84 121  43  79]]


[[3, 2, 76, 100, 54, 43], [102, 85, 25, 61, 51, 75], [10, 67, 84, 121, 43, 79]]

In [19]:
def to_list(A):
    if len(A.shape)>1:
        return[to_list(x) for x in A]
    return[x for x in A]
to_list(A)

[[182, 251, 13, 179, 66, 232],
 [254, 239, 137, 220, 99, 219],
 [83, 53, 173, 159, 84, 45],
 [122, 128, 8, 61, 107, 38],
 [148, 158, 231, 24, 94, 217]]

In [24]:
##Q2
def diagonale(A):
    c=min(A.shape)
    s=0
    for i in range(c):
        s=s+A[i, i]
    return s  
diagonale(A)
    

749

In [22]:
##Q2'
A.trace()
np.sum(A.diagonal())

749

In [30]:
##Q3
def greater(A, x):
    return A[A>x].tolist()
greater(A,100)

[182,
 251,
 179,
 232,
 254,
 239,
 137,
 220,
 219,
 173,
 159,
 122,
 128,
 107,
 148,
 158,
 231,
 217]

In [53]:
##Q4
def add(A, B):
    if A.shape!= B.shape:
        print('shapes must be equal')
        return None
    x,y = A.shape
    c=np.zeros((x, y))
    for i in range(x):
        for j in range(y):
            c[i, j] = A[i, j]+B[i, j]
    return c
add(A, B)== A+B


array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [63]:
##Q5
def subtractMean(A):
    return A - A.mean(axis=1, keepdims=True)
subtractMean(np.eye(5))

array([[ 0.8, -0.2, -0.2, -0.2, -0.2],
       [-0.2,  0.8, -0.2, -0.2, -0.2],
       [-0.2, -0.2,  0.8, -0.2, -0.2],
       [-0.2, -0.2, -0.2,  0.8, -0.2],
       [-0.2, -0.2, -0.2, -0.2,  0.8]])